# Generated by Django 2.2.4 on 2019-10-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventColorDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('gray', 'Gray')], unique=True)),
                ('description', models.TextField()),
                ('index', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('begin',)},
        ),
        migrations.CreateModel(
            name='EventColorMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.TextField()),
                ('case_sensitive', models.BooleanField(default=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.EventColorDescription')),
            ],
            options={
                'ordering': ('color__index',),
            },
        ),
    ]
